#!/bin/bash
filenames=(begin.v
rule.v
play.v
argument.n
bank.n
produce.v
important.a
judgment.n
wash.v
use.v
lose.v
provide.v
suspend.v
express.v
audience.n
party.n
remain.v
disc.n
appear.v
degree.n
paper.n
shelter.n
talk.v
climb.v
organization.n
arm.n
expect.v
watch.v
atmosphere.n
miss.v
treat.v
add.v
source.n
performance.n
ask.v
activate.v
hot.a
sort.n
receive.v
interest.n
solid.a
difficulty.n
image.n
write.v
win.v
decide.v
simple.a
note.v
different.a
hear.v
mean.v
eat.v
operate.v
difference.n
encounter.v
smell.v
plan.n)
for word in ${filenames[@]}
do
	echo $word
	java weka.classifiers.meta.Bagging -P 100 -S 1 -num-slots 1 -I 10 -W weka.classifiers.trees.J48 -t trainData/$word.arff -T testData/$word.arff -c 1 -classifications "weka.classifiers.evaluation.output.prediction.CSV" > predictions/$word.pred
		
done
rm kaggle.csv
for word in ${filenames[@]}
do
	tail -n +6 predictions/$word.pred | awk -F"," '{print $3}' | cut -d: -f2 | awk -v ORS="" '{gsub(/./, "&\n"); print}' >> kaggle.csv
done
